### ISSUE TITLE
Crash when pressing shift and the interact hotkey after removing glasses from baubles slot

### ISSUE THREAD

**Issue by djpadbit** [StarChasers/OCGlasses#66] opened 2019-07-03 20:31 UTC
As the title says, when i remove the glasses after having them in the baubles slot and i press shift and the interaction key, the game crashes. I am playing on a server, but i can recreate the crash on a singleplayer world.

Also, i should probably make another issue but i figured i'd put it here. The glasses gui don't update when you add a host on a server, you have to relog to be able to manage the added hosts. It works fine on a singleplayer world though.
Edit: It seems to work fine when right clicking the terminal without a helmet witch links the glasses and equips them

Opencomputer version: 1.7.4.153
Openglasses version: 2.1.1-6
Baubles version: 1.5.2
Forge version: 14.23.5.2836
Crash report: [crash-2019-07-03_21.58.14-client.txt](https://github.com/StarChasers/OCGlasses/files/3356669/crash-2019-07-03_21.58.14-client.txt)

**Comment by ben-mkiv** [comment] 2019-07-04 10:42
the first issue is fixed in the build that i've linked in your other bug report.

but i can't reproduce the 2nd one. What exactly did you do? Started linking with `component.glasses.startLinking()` but it didn't show up in the upper list when you accepted the link?

**Comment by djpadbit** [comment] 2019-07-04 12:55
I just right clicked the terminal with the glasses to link it and it doesn't show up in the hosts in the glasses gui but when i relog on the server it shows up. It works fine when i right click with no helmet witch links the terminal it and equips it.

**Comment by ben-mkiv** [comment] 2019-07-04 18:18
so this build should also fix your 2nd issue
http://ci.pc-logix.com/job/OCGlasses/17/artifact/build/libs/OpenGlasses-MC1.12.2-2.1.1-17.jar

**Comment by djpadbit** [comment] 2019-07-04 22:28
I just tried it out on my server and all the issues seems to be fixed.

**Comment by ben-mkiv** [comment] 2019-07-06 13:17
fixed build is now also on curseForge
https://www.curseforge.com/minecraft/mc-mods/openglasses2/files

**Closed as completed by ben-mkiv** 2019-07-06 13:17 UTC
Labels: bug
