### ISSUE TITLE
Add OpenGL-esk triangle strip widget.

### ISSUE THREAD

**Issue by elijahlorden** [StarChasers/OCGlasses#35] opened 2017-07-24 22:26 UTC
In OpenGL you can pass the renderer a list of vertices to be rendered in one call, rather than many calls for each individual triangle.  I propose a widget that takes an table of vertices in it's initializer and renders them all at once.  The table would be a simple numeric array {#, #, #, #, #, #, #, #, #}, with each set of 3 numbers representing a triangle.

**Comment by Kubuxu** [comment] 2017-07-25 09:58
It is done in the backend.

**Comment by elijahlorden** [comment] 2017-08-11 13:00
Is it possible for this to be directly accessible via the LUA API?

**Comment by Kubuxu** [comment] 2017-08-11 14:01
No that I know of.

**Comment by marcin212** [comment] 2017-09-18 13:39
Duplicate of #15

**Comment by ben-mkiv** [comment] 2018-08-16 23:45
supported by OpenGlasses2 (custom shapes)
https://minecraft.curseforge.com/projects/openglasses2

https://github.com/StarChasers/OCGlasses/wiki/Widget_Custom2D
https://github.com/StarChasers/OCGlasses/wiki/Widget_Custom3D

**Closed as completed by ben-mkiv** 2018-08-16 23:45 UTC
Labels: duplicate, enhancement
